version: '3.3'

services:
  app:
    build: .
    container_name: school-absent-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: casaos
      DB_PASSWORD: casaos
      DB_NAME: school_absent
      DB_PORT: 5432
      SESSION_SECRET: xaM78fkcKGx/MdPkAc97FPXSBLOycwA2qyN8brHXZOc=
      NODE_ENV: development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  postgres_data:
